### ISSUE TITLE
Move this

### ISSUE THREAD

**Issue by janv** [janv/gulp-fingerprint#1]
@trodrigues Mind moving the sourcemap branch of this fork into the contentful org and adapting the package.json in user_interface?

**Comment by trodrigues** [comment]
Sure, I'll take care of this on Monday and I'll let you know.

**Comment by trodrigues** [comment]
Done.

**Comment by janv** [comment]
So, I can delete this, yes?

**Comment by trodrigues** [comment]
Yep, go ahead.

On Mon, May 4, 2015 at 10:06 AM, Jan Varwig notifications@github.com
wrote:

> So, I can delete this, yes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/janv/gulp-fingerprint/issues/1#issuecomment-98621313.

## 

Tiago Rodrigues
http://trodrigues.net
IM: tmcrodrigues@gmail.com
Skype: trodrigues.net
